### ISSUE TITLE
It seems that simply remove the local windows leads to better performance ?

### ISSUE THREAD

**Issue by sxbkdby8** [graphcore-research/llm-inference-research#3]
Hello, I try to simply set local_window_size = 0 and it performs a little bit better in QA tasks,Is there anything here that I'm wrong about?

**Comment by DouglasOrr** [comment]
Hi! Thanks for sharing - that sounds plausible. We didn't extensively ablate `local_k`, so it's like that for many (model, task) pairs, it can be set to zero. I've found some of our [notebooks from early investigations](https://github.com/graphcore-research/llm-inference-research/blob/notebooks/2023-sparse-attention/rmoe-58-local-k/AnalyseLocal.ipynb), which were inconclusive for the (incomplete) SparQ method `ann_sparse_q`, but as expected `local_k` is essential for H2O (`eviction_sum_weight`).

So the choice to set `local_k = k / 4` as a general rule in SparQ was more because it seemed a marginally safer design choice. With small gains and multiple (model, task) pairs, it would require many more tests to be scientific about this rule. But I think it is likely safe to set `local_k = 0`, if it seems to work in a given setting.

**Comment by sxbkdby8** [comment]
I got it. Thank you for your response! Your help is greatly appreciated.
